### ISSUE TITLE
Some intersting sphinx extensions

### ISSUE THREAD

**Issue by seisman** [seismo-learn/seismology101#112]
1. https://github.com/sbrunner/sphinx-prompt
2. https://sphinx-tabs.readthedocs.io/en/latest/
3. https://sphinx-hoverxref.readthedocs.io/en/latest/

I didn't read the documentation carefully, but the examples look interesting. 

Please check the live sites for how it works, then we can discuss if we want to use these extensions.

**Comment by core-man** [comment]
The second one may be useful.

**Comment by seisman** [comment]
FYI, `sphinx-hoverxref` only works on the ReadTheDocs server, so we can't use it.

**Comment by seisman** [comment]
> The second one may be useful.

I can see that it's very useful in software.

**Comment by seisman** [comment]
Should we add sphinx-tabs to the "seismology" repository so that all the three documentation have the same configurations?

**Comment by core-man** [comment]
> Should we add sphinx-tabs to the "seismology" repository so that all the three documentation have the same configurations?

yes
