### ISSUE TITLE
Recommend pkgs.org

### ISSUE THREAD

**Issue by seisman** [seismo-learn/seismology101#120]
Https://pkgs.org is a useful site for searching for Linux packages. We should recommend it somewhere.

**Comment by core-man** [comment]
Yes~ Perhaps in Linux101.

**Comment by seisman** [comment]
What about recommending this site when talking about `dnf` (https://seismo-learn.org/seismology101/computer/fedora-setup/#id5) and `apt` (https://seismo-learn.org/seismology101/computer/ubuntu-setup/#id5).

**Comment by core-man** [comment]
> What about recommending this site when talking about `dnf` (https://seismo-learn.org/seismology101/computer/fedora-setup/#id5) and `apt` (https://seismo-learn.org/seismology101/computer/ubuntu-setup/#id5).

That's good. In this way, we may also recommend https://brew.sh/ when talking about `brew` (https://seismo-learn.org/seismology101/computer/macos-setup/#id4)

**Comment by seisman** [comment]
> That's good. In this way, we may also recommend https://brew.sh/ when talking about `brew` (https://seismo-learn.org/seismology101/computer/macos-setup/#id4)

I would like to recommend https://formulae.brew.sh/ instead.
