### ISSUE TITLE
tldr command does not work

### ISSUE THREAD

**Issue by zhaozhiyuan1989** [seismo-learn/seismology101#128]
```
sudo dnf install tldr
tldr dos2unix
```
The command may return  `Error fetching from tldr: <urlopen error [Errno 111] Connection refused>`

**Comment by seisman** [comment]
Which one doesn't work? The first one or the second one?

**Comment by zhaozhiyuan1989** [comment]
> Which one doesn't work? The first one or the second one?

The second one.

**Comment by seisman** [comment]
I have this on macOS:
```
$ tldr dos2unix
This page doesn't exist yet!
Submit new pages here: https://github.com/tldr-pages/tldr
```
tldr has many different implementations. The Homebrew tldr is written in C, Fedora tldr is written in Python and Ubuntu tldr is written in Haskell.

I think the Python one may report the error when tldr doesn't provide the dos2unix manpage.

**Comment by seisman** [comment]
If `tldr tar` works, then it's not a bug.

**Comment by core-man** [comment]
We may note this issue in https://seismo-learn.org/seismology101/computer/commands/.

**Comment by seisman** [comment]
> We may note this issue in https://seismo-learn.org/seismology101/computer/commands/.

Changing "其以实例的方式展示了命令的常见用法。" to "其以实例的方式展示了大多数常用命令的常见用法。"

**Comment by core-man** [comment]
> 其以实例的方式展示了大多数常用命令的常见用法。

"其以实例的方式展示了大多数常用命令的常见用法，某些命令可能还未编写。"

**Comment by seisman** [comment]
OK to me.

**Comment by zhaozhiyuan1989** [comment]
其实我想表达的是，在国内可能有的 Linux 发行版的 tldr 无法从网上下载 man page。

Ubuntu 上执行查询命令后会自动从 github 克隆 man page 到本地，克隆完成后即可查询，

不知道 Fedora 是什么工作方式，在我这里什么无论查询什么命令都会报错。

**Comment by seisman** [comment]
Is it because github is blocked?

**Comment by core-man** [comment]
If zhiyuan cannot use it for any command, it is possible that github is blocked. How about it if you use your phone DATA to connect to the internet? @zhaozhiyuan1989

**Comment by zhaozhiyuan1989** [comment]
我在 WSL Ubuntu20.04LTS 上是可以正常从 GitHub 下载更新 tldr 的 man page，但是 Fedora 直接报错

**Comment by core-man** [comment]
I can use `trdl` in Fedora and Ubuntu in the Virtual Machine under my macOS.

**Comment by zhaozhiyuan1989** [comment]
所以就是网络问题

**Comment by seisman** [comment]
Closing as we can do nothing.
