### ISSUE TITLE
Recommend ack

### ISSUE THREAD

**Issue by seisman** [seismo-learn/seismology101#142]
[ack](https://beyondgrep.com/) is similar to `grep`, but better.

It's very powerful and has many options, but I only use it in its simplest case.

```
ack pattern
```

There are also many other similar tools (see https://blog.burntsushi.net/ripgrep/), but I never tried them.

**Comment by core-man** [comment]
This command is really cool.

**Comment by seisman** [comment]
There are two places to recommend ack:

1. In the setup sections (a few sentences)
2. A new section for introducing these useful command-line tools. (a longer tutorial).

Currently, I prefer option 1.

**Comment by core-man** [comment]
> There are two places to recommend ack:
> 
> 1. In the setup sections (a few sentences)
> 2. A new section for introducing these useful command-line tools. (a longer tutorial).
> 
> Currently, I prefer option 1.

I prefer option 1. But don't we want to add a short tutorial in the `command` page?

**Comment by seisman** [comment]
I don't want to make the 101 too long...

**Comment by core-man** [comment]
> I don't want to make the 101 too long...

Okay.
