### ISSUE TITLE
Tutorials for commonly used seismological software

### ISSUE THREAD

**Issue by core-man** [seismo-learn/seismology101#143]
We may recommend some software, e.g.,

- SOD
- ObsPy
- SAC
- GMT & PyGMT
- TauP

We can give a brief introduction and some simple examples. We have to choose those basic points which new babies must know. New babies can then use those software in seismological exercises and grasp them. After finish this tutorial, they can dig more on other websites if they need more advanced skills.

References
- https://migg-ntu.github.io/SeisTomo_Tutorials/seismology/seismological-tools/index.html

**Comment by core-man** [comment]
Do we really want to maintain some simple tutorial tutorials on https://seismo-learn.org/seismology101/seismology/software/?

Or we can just make a list and a simple summary for each software?

**Comment by seisman** [comment]
Of course not, all software tutorial should be included in the "software" repo. 

Even for obspy, which is extensively used in the "exercise" chapter, we just show the basic workflow for data request, process and plotting, rather than a lengthy tutorial.

**Comment by core-man** [comment]
> Of course not, all software tutorial should be included in the "software" repo.
> 
> Even for obspy, which is extensively used in the "exercise" chapter, we just show the basic workflow for data request, process and plotting, rather than a lengthy tutorial.

Sound good. I will submit a PR to just list those software later.
