### ISSUE TITLE
Sphinx extensions and themes

### ISSUE THREAD

**Issue by seisman** [seismo-learn/seismology101#144]
Sphinx extensions that we may be interested in:

1. https://sphinx-togglebutton.readthedocs.io/en/latest/
2. https://sphinx-copybutton.readthedocs.io/en/latest/ (added to seismology101 and software)
3. https://sphinx-panels.readthedocs.io/en/latest/

Sphinx theme that we may be interested in:

1. https://sphinx-book-theme.readthedocs.io/en/latest/

Please check the live demo and tell me what you think about them.

**Comment by core-man** [comment]
> 1. https://sphinx-togglebutton.readthedocs.io/en/latest/

I don't know when we'd like to hide something.

> 2. https://sphinx-copybutton.readthedocs.io/en/latest/

This is great.

> 3. https://sphinx-panels.readthedocs.io/en/latest/

This is also useful and makes pages clear. 

> Sphinx theme that we may be interested in:
> 
> 1. https://sphinx-book-theme.readthedocs.io/en/latest/

This may be used to write `seismology` and some courses.

**Comment by seisman** [comment]
Do we want to add sphinx-copybutton to seismology?

**Comment by core-man** [comment]
> Do we want to add sphinx-copybutton to seismology?

We may wait until we use it in 101.

**Comment by seisman** [comment]
> > Do we want to add sphinx-copybutton to seismology?
> 
> We may wait until we use it in 101.

We already use it in 101.

![image](https://user-images.githubusercontent.com/3974108/106548260-ad6b3880-64dc-11eb-8f0d-06f0094bd3c4.png)

**Comment by core-man** [comment]
> > > Do we want to add sphinx-copybutton to seismology?
> > 
> > 
> > We may wait until we use it in 101.
> 
> We already use it in 101.
> 
> ![image](https://user-images.githubusercontent.com/3974108/106548260-ad6b3880-64dc-11eb-8f0d-06f0094bd3c4.png)

This one is great. Please add it in seismology.

**Comment by seisman** [comment]
> This one is great. Please add it in seismology.

But we probably will never write codes in seismology, no?

**Comment by core-man** [comment]
> > This one is great. Please add it in seismology.
> 
> But we probably will never write codes in seismology, no?

We may write some snippet I guess.

**Comment by core-man** [comment]
> > This one is great. Please add it in seismology.
> 
> But we probably will never write codes in seismology, no?

Or we can add it when we write codes. It is easy.

**Comment by seisman** [comment]
> > > This one is great. Please add it in seismology.
> > 
> > 
> > But we probably will never write codes in seismology, no?
> 
> Or we can add it when we write codes. It is easy.

OK.

**Comment by core-man** [comment]
Sorry, I didn't find usage of `container` and `column` in sphnix-panels.

**Comment by seisman** [comment]
https://sphinx-panels.readthedocs.io/en/latest/#grid-layout 

It's here, but to understand it, you have to know more about [Bootstrap](https://getbootstrap.com/).

I just made some explanation in https://github.com/seismo-learn/seismology101/pull/155#issue-566420468.

**Comment by seisman** [comment]
You can try to resize the width of your web browser to see how the columns of panels change with width.

You can also use the developer tools to preview it on mobile phones and iPad.

![image](https://user-images.githubusercontent.com/3974108/106688759-b8859d80-659c-11eb-85b5-19a913b665d4.png)

**Comment by core-man** [comment]
I see.

**Comment by seisman** [comment]
One of the possible use cases is in "software":

**Before**
![image](https://user-images.githubusercontent.com/3974108/106778072-954a0500-6613-11eb-9f63-667974c28f96.png)

**After**
![image](https://user-images.githubusercontent.com/3974108/106778291-d04c3880-6613-11eb-9aec-5f2372e7746a.png)

**Comment by core-man** [comment]
> One of the possible use cases is in "software":
> 
> **Before**
> ![image](https://user-images.githubusercontent.com/3974108/106778072-954a0500-6613-11eb-9f63-667974c28f96.png)
> 
> **After**
> ![image](https://user-images.githubusercontent.com/3974108/106778291-d04c3880-6613-11eb-9aec-5f2372e7746a.png)


okay

**Comment by seisman** [comment]
Close this issue, as we already added sphinx-copybutton and sphinx-panels. We won't add sphinx-togglebutton, because sphinx-panels already has a similar feature.

We will explore the sphinx-book-theme in #153
