### ISSUE TITLE
Add reStructuredText cheatsheet

### ISSUE THREAD

**Issue by core-man** [seismo-learn/seismology101#149]
We may add some commonly used rst rules so that other contributor may follow.

- https://docs.generic-mapping-tools.org/latest/rst-cheatsheet.html

**Comment by seisman** [comment]
It's easy to have the cheatsheet, but I'm not sure where to put it.

We have three sphinx documentation, and we definitely don't want to maintain three copies.

**Comment by seisman** [comment]
> We have three sphinx documentation, and we definitely don't want to maintain three copies.

We have the same issue with contributing guidelines (#111).

**Comment by core-man** [comment]
> It's easy to have the cheatsheet, but I'm not sure where to put it.
> 
> We have three sphinx documentation, and we definitely don't want to maintain three copies.

We may put all the common things in one new repo and link to it.

**Comment by seisman** [comment]
Not a bad idea. Some other organizations also do things like this.

We need to build a new sphinx site called "contributing"?

**Comment by core-man** [comment]
> Not a bad idea. Some other organizations also do things like this.
> 
> We need to build a new sphinx site called "contributing"?

We may not only put contributing in that repo. So maybe "Notes"?

A quick TOC:

- reStructuredTexT cheatsheet
- common contributing notes for all websites
- special contributing notes for each website

**Comment by seisman** [comment]
> We may not only put contributing in that repo. So maybe "Notes"?
> Or we may first name it "contributing" and rename it if needed.
> 
> A quick TOC:
> 
> * reStructuredTexT cheatsheet
> * common contributing notes for all websites
> * special contributing notes for each website

Sounds a good idea. Do you want to create another sphinx repository?

**Comment by core-man** [comment]
> > We may not only put contributing in that repo. So maybe "Notes"?
> > Or we may first name it "contributing" and rename it if needed.
> > A quick TOC:
> > 
> > * reStructuredTexT cheatsheet
> > * common contributing notes for all websites
> > * special contributing notes for each website
> 
> Sounds a good idea. Do you want to create another sphinx repository?

Okay~

**Comment by core-man** [comment]
We will add reStructuredText cheatsheet in https://github.com/seismo-learn/contributing.

See seismo-learn/contributing#1.
