### ISSUE TITLE
Bump peter-evans/find-comment and peter-evans/create-or-update-comment

### ISSUE THREAD

**Issue by core-man** [seismo-learn/seismology101#152]
Shall we bump peter-evans/find-comment and peter-evans/create-or-update-comment to new versions?
Now we use v1.

- v1.2.0: https://github.com/peter-evans/find-comment/releases
- v1.4.4: https://github.com/peter-evans/create-or-update-comment/releases

**Comment by seisman** [comment]
v1 always points to the latest v1.x.x versions, so we don't need to bump these versions.

**Comment by core-man** [comment]
> v1 always points to the latest v1.x.x versions, so we don't need to bump these versions.

Soga~
