### ISSUE TITLE
Split the workflow into two separate workflow

### ISSUE THREAD

**Issue by seisman** [seismo-learn/seismology101#165]
Currently, we have one single workflow, which does two different jobs:

1. On the **main** branch, it builds the website and deploys to gh-pages branch
2. In PRs, it builds the website, deploys the PR preview site, and make comments

As you can see, these two jobs have some common steps, including "Cancel Previous Runs", "Set up Python", "Install dependencies", and "Build sphinx document". I wrote the two jobs in one workflow, so that we don't need to repeat the common steps.

However, it seems the workflow is becoming more and more complicated. And we have to check if `github.event_name == 'pull_request_target'` or `github.event_name == 'push'` in many steps. Perhaps we should put the two jobs into two workflows.

**Pros**:

- Easier to read and understand
- Shorter for each workflow

**Cons**:

- Need to maintain two workflows
- Need to repeat the common steps in two workflows

Thoughts?

**Comment by core-man** [comment]
If it is simple, we should keep it in just one workflow that is easy to maintain.

However, now the single one is a little complicated. I think it is not a big deal to maintain two workflows if
they are easier to understand and maintain. Meanwhile, the common parts are stable and we usually won't need
to revise them, right?

So I vote for two workflows.

**Comment by seisman** [comment]
> However, now the single one is a little complicated. I think it is not a big deal to maintain two workflows if
> they are easier to understand and maintain. Meanwhile, the common parts are stable and we usually won't need
> to revise them, right?

Yes.

**Comment by seisman** [comment]
Done in #167
