### ISSUE TITLE
Add tutorials for seimic source

### ISSUE THREAD

**Issue by core-man** [seismo-learn/seismology101#17]
- [x] Introduction
- [ ] ~~Catalog format~~
- [x] Global and regional catalogs (https://github.com/seismo-learn/seismology101/pull/566)
- [ ] Add a figure showing the difference between hypocenter and epicenter. (https://github.com/seismo-learn/seismology101/pull/567)

reference
- https://migg-ntu.github.io/SeisTomo_Tutorials/seismology/seismic-source/index.html

**Comment by seisman** [comment]
Also need to add a figure showing the difference between hypocenter and epicenter.
