### ISSUE TITLE
Intel oneAPI bug

### ISSUE THREAD

**Issue by core-man** [seismo-learn/seismology101#176]
It seems that Intel OneAPI will also install python and conda. If we set environments for OneAPI, we may automatically use Intel conda and python.

**Comment by seisman** [comment]
What is the path and Python version?

**Comment by core-man** [comment]
When I comment Intel OneAPI in `.zshrc`:
```
$ which conda 
~/.anaconda3/condabin/conda
$ which python
/usr/bin/python
$ conda activate seis
(seis) $ which python
~/.anaconda3/envs/seis/bin/python
(seis) $ python --version
Python 3.8.5
```

When I set Intel OneAPI in `.zshrc` after `anaconda`:
```
$ which conda
/opt/intel/oneapi/intelpython/latest/bin/conda
$ which python
/opt/intel/oneapi/intelpython/latest/bin/python
$ python --version
Python 3.7.9 :: Intel Corporation
$ conda activate seis
Could not find conda environment: seis
You can list all discoverable environments with `conda info --envs`.
```

When I set Intel OneAPI in `.zshrc` before `anaconda`:
```
$ which conda 
/opt/intel/oneapi/intelpython/latest/bin/conda
$ which python
/opt/intel/oneapi/intelpython/latest/bin/python
$ python --version
Python 3.7.9 :: Intel Corporation
$ conda activate seis
(seis) $ which conda 
/opt/intel/oneapi/intelpython/latest/condabin/conda
(seis) $ which python
~/.anaconda3/envs/seis/bin/python
(seis) $ python --version
Python 3.8.5
```

For the last case, we use Intel's conda but we use the environment created by `anaconda`.

**Comment by seisman** [comment]
So Intel OneAPI also installs the conda tools, it means that Intel OneAPI users don't need to install anaconda anymore, right?

**Comment by core-man** [comment]
> So Intel OneAPI also installs the conda tools, it means that Intel OneAPI users don't need to install anaconda anymore, right?

I think so, but I don't know if intel conda is a little different.

**Comment by seisman** [comment]
I believe it's the same, but maybe older versions. 

Do you want to uninstall your anaconda, and try the intel one in your research?

**Comment by core-man** [comment]
> I believe it's the same, but maybe older versions.
> 
> Do you want to uninstall your anaconda, and try the intel one in your research?

Not now. Maybe I can do it when I finish the project in one or two months.
We can just put OneAPI before anaconda in `.zshrc` now so that we can use both
OneAPI and anaconda. I will add a note in OneAPI.

**Comment by seisman** [comment]
> I will add a warning in OneAPI setup.

Sounds good.

**Comment by core-man** [comment]
Close it since we only install `icc` and `ifort` now? See https://github.com/seismo-learn/seismology101/pull/383#discussion_r720302386

**Comment by seisman** [comment]
I think we can close it after we finish all the Intel sections.
