### ISSUE TITLE
Seismological practices for distance and angle

### ISSUE THREAD

**Issue by core-man** [seismo-learn/seismology101#204]
We often have to calculate the distance and angle (e.g., baz and az) between two locations, e.g., station and event, when we process and analyze seismic data. We can use the tutility, [distaz](https://seismo-learn.org/software/utilities/distaz/), in the command line. We can also use [gps2dist_azimuth](https://docs.obspy.org/packages/autogen/obspy.geodetics.base.gps2dist_azimuth.html#obspy.geodetics.base.gps2dist_azimuth) and [kilometers2degrees](https://docs.obspy.org/packages/autogen/obspy.geodetics.base.kilometers2degrees.html#obspy.geodetics.base.kilometers2degrees) in [obspy.geodetics](https://docs.obspy.org/packages/obspy.geodetics.html).

Two examples can be presented:
- [ ] distaz
- [ ] ObsPy

**Comment by wangliang1989** [comment]
听说sac里有一个distaz，用的是椭球地球模型，可能更准

**Comment by core-man** [comment]
> 听说sac里有一个distaz，用的是椭球地球模型，可能更准

Yes, SAC has a [distaz](https://seisman.github.io/SAC_Docs_zh/libs/libsacio/#distaz). However, both @seisman and I think that we should recommend ObsPy instead of SAC to new babies. Currently, we only use SAC to pick phases or other cases that need GUI. It is very friendly and useful to process and analyze seismic data using Python and Obspy. So I think we don't need to recommend the `distaz` in SAC.

---

I don't think SAC's `distaz` is better than [`distaz`](https://seismo-learn.org/software/utilities/distaz/) and [`gps2dist_azimuth`](https://docs.obspy.org/packages/autogen/obspy.geodetics.base.gps2dist_azimuth.html#obspy.geodetics.base.gps2dist_azimuth).

See line 94-95 in `SAC101.6/src/ucf/distaz.c`:
```C
static float rad = 6378.160;  /* Earth Radius */                                              
static float fl = 0.00335293; /* Earth Flattening */ 
```
[`gps2dist_azimuth`](https://docs.obspy.org/packages/autogen/obspy.geodetics.base.gps2dist_azimuth.html#obspy.geodetics.base.gps2dist_azimuth) uses `a=6378.1370` and `f=0.0033528106647474805` (WGS84 ellipsoid) by default, and can accept other `a` and `f`. [`distaz`](https://seismo-learn.org/software/utilities/distaz/) uses `f=0.003352813178` (see line 67 in [distaz.c](http://www.seis.sc.edu/software/distaz/distaz.c)). It seems that `gps2dist_azimuth` is the best one.

**Comment by core-man** [comment]
@seisman Shall we start the first exercise with this tutorial? it seems simple and commonly used.

**Comment by seisman** [comment]
Yes, we can draft an outline first.

**Comment by seisman** [comment]
Closed by https://github.com/seismo-learn/seismology101/pull/440.
