### ISSUE TITLE
Some planned seismological exercises

### ISSUE THREAD

**Issue by core-man** [seismo-learn/seismology101#205]
# A List of Planned Seismological Exercises

We could finish those sections which all of us think are necessary and important, while leaving the other to be discussed later.  **Please update/remove/revise it directly!**

## Introduction

- [x] A cartoon showed the whole seismic data workflow
- [x] A workflow summary

## Earthquake catalog
- [ ] How to search and download the earthquake catalog
- [ ] Catalog I/O or format conversion
- [ ] Plot earthquake locations: map view and cross-section

## Station Metadata
- [ ] How to search and download metadata
- [ ] Station Metadata I/O or format conversion
- [ ] Plot station distribution
- [ ] Plot instrument response

### Data download and pre-process
- [ ] Download data: FDSNWS #308
- [ ] Basic processing 
  - [ ] format conversion
  - [ ] merge
  - [ ] rename
  - [ ] time zone correction
  - [ ] event information
  - [ ] metadata
  - [ ] remean/rtrend/tape
  - [ ] remove response
  - [ ] trim
  - [ ] rotate
  - [ ] resample
  - [ ] filter
  - [ ] predicted arrival time

**References**:
- https://seisman.github.io/SAC_Docs_zh/data-process/
- https://github.com/xumi1993/seispy
- https://github.com/MIGG-NTU/SeisData_Tools/blob/main/workshops/SeisTomo_Tutoriala_DATA/data-process/date-process.ipynb
- https://github.com/uafgeotools/pysep

### Data analysis
- [ ] Plot waveform data
  - [ ] `gmt sac`
  - [ ] ObsPy
- [ ] phase picking
  - [ ] manual picking
  - [ ] automatic picking
    - [ ] STA/LTA: ObsPy, https://github.com/xumi1993/STALTA
- [ ] cross-correlation
- [ ] waveform stacking

## Other

We need to think further about where to put those exercises.

- [ ] distance and angle #204
- [ ] travel time curve
- [ ] travel time path

**Comment by core-man** [comment]
I think we should give this issue a higher priority than the seismology part. I find quite a few new babies need it more than the seismological basics.

**Comment by wangliang1989** [comment]
打算用什么软件画数据处理的cartoon呢

**Comment by core-man** [comment]
> 打算用什么软件画数据处理的cartoon呢

PPT

**Comment by seisman** [comment]
I've attached the slide for the seismic workflow, so that we can further improve it:

![image](https://user-images.githubusercontent.com/3974108/175798279-9da5d51b-e0b6-45c6-b5f5-e8bbeb75560c.png)

[workflow.pptx](https://github.com/seismo-learn/seismology101/files/8985927/workflow.pptx)

**Comment by seisman** [comment]
I've split this PR into a series of small PRs, so that we can better focus on one section in each PR. 

Closing the issue.
