### ISSUE TITLE
Chinese translation for introduction

### ISSUE THREAD

**Issue by core-man** [seismo-learn/seismology101#207]
Currently, we translate "introduction" to be 前言 for programming, seismology, and best practices. But it is preface in English for 前言. Shall we use another one, e.g., 简介 or 概述? I prefer 简介.

Meanwhile, we use `best-practices/index.rst` as the introduction page. Shall we rename it as `/best-practices/introduction.rst`?

**Comment by wangliang1989** [comment]
我觉得中文中的前沿是变着花样地说“这本书非常好”。英文中的intro应该是引言、引论、概述的意思。我倾向于用introduction.rst，我觉得index是索引，目录之类的东西。
