### ISSUE TITLE
ARM架构的Mac的系统安装

### ISSUE THREAD

**Issue by wangliang1989** [seismo-learn/seismology101#219]
根据我的测试，发现有以下问题：

xcode-select --install我装了两次git才安装好

brew搜索不到visual-studio-code

**Comment by wangliang1989** [comment]
文档内的软件有一半我都不需要，我并没有试验，如果你们想试验，可以试验

**Comment by core-man** [comment]
> xcode-select --install我装了两次git才安装好
> 
> brew搜索不到visual-studio-code

Thanks. I don't have an ARM macOS now. Will have a try when I have a new one this year or next year.

**Comment by seisman** [comment]
> brew搜索不到visual-studio-code

Did you use `brew install visual-studio-code` or `brew install --cask visual-studio-code`?

**Comment by wangliang1989** [comment]
![image](https://user-images.githubusercontent.com/12059719/112427530-b3f78d00-8d74-11eb-8453-e09e47a68e50.png)
我刚刚重新做的结果。我现在已经手动下载vscode装了

**Comment by seisman** [comment]
墙的问题，与homebrew无关

**Comment by wangliang1989** [comment]
我不觉得。我刚刚装了另外两个软件
![image](https://user-images.githubusercontent.com/12059719/112428023-82cb8c80-8d75-11eb-970d-5ceba6a9f3fd.png)

**Comment by seisman** [comment]
![image](https://user-images.githubusercontent.com/3974108/112428327-5f6ef600-8d11-11eb-8af0-65eadba0eaf1.png)

GUI软件与命令行软件不同。Homebrew 是到 VSCode 网站下载的原安装包，而原安装包是被重定向到另一个网站。下载过程中下载失败。

**Comment by wangliang1989** [comment]
Though the mirror of USTC is set, hb downloads GUI softwares from other website?

**Comment by seisman** [comment]
Yes.

**Comment by wangliang1989** [comment]
我建议文档对这一点进行说明：即便使用了国内的镜像，也有可能软件下载失败。

**Comment by seisman** [comment]
没必要。
