### ISSUE TITLE
Updates on compatibility of WSL2 & 3rd party virtual machine applications

### ISSUE THREAD

**Issue by acotor** [seismo-learn/seismology101#220]
[WSL 2 FAQs](https://docs.microsoft.com/en-us/windows/wsl/wsl2-faq#will-i-be-able-to-run-wsl-2-and-other-3rd-party-virtualization-tools-such-as-vmware--or-virtualbox-) updates that both VirtualBox and VMware have released versions that support Hyper-V and WSL2.

[Comparing WSL 1 and WSL 2](https://docs.microsoft.com/en-us/windows/wsl/compare-versions#performance-across-os-file-systems) updates that WSL 2 will work with VMware 15.5.5+ and VirtualBox 6+.

So the chapter [WSL 配置指南](https://github.com/seismo-learn/seismology101/blob/a995d785e7df5e3356550e25ddcfaa8c08f494a6/source/computer/wsl-setup.rst) needs an update.

**Comment by core-man** [comment]
@acotor Thanks a lot for the updates. Would you like to submit a PR to revise the documentation based on the updates?

**Comment by acotor** [comment]
@core-man I'm sorry since I've been busy recently. And, I'm not quite clear about the procedure on editing and previewing the .rst documentation on local.
I would like to contribute later if possible. Your project is great and students who major on this can get true benefits.

**Comment by core-man** [comment]
@zhaozhiyuan1989 Would you like to work on this issue since @acotor has not replied to our request for one week?

**Comment by seisman** [comment]
Personal communication with Zhiyuan:

> 官网上确实有说明新版本的虚拟机可以和WSL2共存，不过我没有尝试过
> 一是要求vm软件是新版本，二是要求win10更新到20H1版本之后，我用1909用的挺好的不太敢更新
> 目前我手头没有可供测试的win10电脑

**Comment by core-man** [comment]
Okay. Let's keep this issue open until someone wants to try it.

**Comment by seisman** [comment]
I think we can trust the official documentation and we just need to update the notes.

**Comment by core-man** [comment]
Okay~ 1~2 sentences with the links above are enough.

**Comment by seisman** [comment]
I'll work on it if you haven't done that.

**Comment by core-man** [comment]
> I'll work on it if you haven't done that.

Please do it.
