### ISSUE TITLE
编译得到的pdf文件名

### ISSUE THREAD

**Issue by wangliang1989** [seismo-learn/seismology101#225]
现在编译为pdf的文件名是sphinx，建议改为seismology101

**Comment by core-man** [comment]
个人觉得目前不会维护 PDF 版本：
1. pdf 的编译、排版比较繁琐，需要额外的精力去处理
2. 我们使用了 sphinx 的某些插件，PDF 无法显示

目前项目刚开始，贡献者人数有限，约 70% 尚未完成。或许可以等到初步完成的时候，再考虑如何维护 PDF 版本。

**Comment by wangliang1989** [comment]
OK
网站还有个很大的问题，我之前给seisman说过，GitHub pages在国内已经处于被墙的状态了

**Comment by core-man** [comment]
这个问题一开始我和冬冬也讨论过，目前的计划是下半年我两回国工作以后把网站托管在国内。现在使用免费的 gh 构建初始版本比较省钱 :smile:

**Comment by wangliang1989** [comment]
服务器的费用科研经费可以报
