### ISSUE TITLE
The site doesn't look correct

### ISSUE THREAD

**Issue by seisman** [seismo-learn/seismology101#226]
![image](https://user-images.githubusercontent.com/3974108/113483270-8f846a80-9470-11eb-9223-3067be3123c7.png)

https://seismo-learn.org/seismology101/

**Comment by wangliang1989** [comment]
我这里也是

**Comment by core-man** [comment]
I just found it.

**Comment by seisman** [comment]
The only difference I can see is docutils had a release a few hours ago, which breaks the sphinx_rtd_theme.

**Comment by seisman** [comment]
https://github.com/readthedocs/sphinx_rtd_theme/issues/1111

**Comment by core-man** [comment]
Some bugs also appear in the lists, e.g., [Zsh](https://seismo-learn.org/seismology101/best-practices/zsh/):

<img width="650" alt="list" src="https://user-images.githubusercontent.com/50591376/113504541-61378580-956b-11eb-8c3a-4f32c6f611ee.png">

also [软件安装：安装路径](https://seismo-learn.org/seismology101/best-practices/software-installation/#id3)

**Comment by core-man** [comment]
Let's reopen this issue because other repos also have such bugs.
