### ISSUE TITLE
Issues with the OS setup guides

### ISSUE THREAD

**Issue by seisman** [seismo-learn/seismology101#243]
In the OS setup guides, the biggest problem is: most software are installed via commands. However, users may not know how to open a terminal or run commands.

**Comment by core-man** [comment]
Good question. We may add how to open a terminal in Linux/macOS in [命令行](https://seismo-learn.org/seismology101/computer/command-line/#id3) and add a link.

**Comment by core-man** [comment]
In macOS setup, we actually indicate that how to open a terminal and run commands: https://seismo-learn.org/seismology101/computer/macos-setup/#command-line-tools-for-xcode
