### ISSUE TITLE
Rethinking the layout of Linux setup guides

### ISSUE THREAD

**Issue by core-man** [seismo-learn/seismology101#245]
Currently, we have two individual Linux setup guides: [Fedora](https://seismo-learn.org/seismology101/computer/fedora-setup/) and [Ubuntu](https://seismo-learn.org/seismology101/computer/ubuntu-setup/#). However, most guides are similar except that we use `dnf` for Fedora and `apt` for Ubuntu. This is not friendly to maintainers. We usually have to revise those similar parts in different files. I am thinking to merge **Fedora** and **Ubuntu** in one file called "Linux 配置指南“ using the sphinx-panel.

Meanwhile, macOS also has a few similar guides as the two Linux distributions, but we may still keep it as a single file until we can find a better way to unify Linux and macOS guides.

**Comment by seisman** [comment]
> I am thinking to merge **Fedora** and **Ubuntu** in one file called "Linux 配置指南“ using the sphinx-panel.

I'm afraid it will be unfriendly to users/readers, as we will use panels so many times in one page.
