### ISSUE TITLE
Install Java Runtime Environment

### ISSUE THREAD

**Issue by core-man** [seismo-learn/seismology101#246]
We have a java runtime environment guide in [seismo-learn/software](https://seismo-learn.org/software/java/) for different OS. I am think we can just add a link to it in OS setup guides ([macOS](https://seismo-learn.org/seismology101/computer/macos-setup/#java), [Fedora](https://seismo-learn.org/seismology101/computer/fedora-setup/#java), [Ubuntu](https://seismo-learn.org/seismology101/computer/ubuntu-setup/#java)) just like we do for [Anaconda](https://seismo-learn.org/software/anaconda/), e.g., [Fedora](https://seismo-learn.org/seismology101/computer/fedora-setup/#python), [Ubuntu](https://seismo-learn.org/seismology101/computer/ubuntu-setup/#python) and [macOS](https://seismo-learn.org/seismology101/computer/macos-setup/#python).

**Comment by seisman** [comment]
I don't want to redirect users to another site just for this simple command.
