### ISSUE TITLE
Install Homebrew M1 Mac

### ISSUE THREAD

**Issue by core-man** [seismo-learn/seismology101#259]
We can add the link ([M1 芯片 Mac 上 Homebrew 安装](https://brew.idayer.com/guide/m1/)) at the note for [Homebrew in M1 Mac](https://seismo-learn.org/sitepreview/seismo-learn/seismology101/homebrew-install/computer/macos-setup/#id3).

**Comment by seisman** [comment]
It's unclear to me why `eval "$(/opt/homebrew/bin/brew shellenv)"` is needed on M1.

Perhaps @wangliang1989 can comment on it?

**Comment by wangliang1989** [comment]
![image](https://user-images.githubusercontent.com/12059719/114115682-df05e300-9915-11eb-91fd-abea52ca76d4.png)
我没执行过那个命令

**Comment by seisman** [comment]
> 我没执行过那个命令。我的环境变量：
> 
> ```
> # brew
> eval "$(/opt/homebrew/bin/brew shellenv)"
> eval "$(/opt/homebrew/bin/brew shellenv)"
> ```
> 
> 我的环境变量是加在zshrc里的

你是指你在 .zshrc 里加了这一句 `eval "$(/opt/homebrew/bin/brew shellenv)"`?

**Comment by wangliang1989** [comment]
嗯，我不知道我为什么写了两次。我刚刚起床，直接给你复制的

**Comment by seisman** [comment]
如果不加会如何？

**Comment by wangliang1989** [comment]
似乎没什么不妥，我把它注释了：
![image](https://user-images.githubusercontent.com/12059719/114118252-13c86900-991b-11eb-93c4-e2286c63b91a.png)

**Comment by seisman** [comment]
这是我执行 brew shellenv 的结果。这个命令只是定义了几个变量而已，感觉没啥用。
```
$ brew shellenv
export HOMEBREW_PREFIX="/usr/local";
export HOMEBREW_CELLAR="/usr/local/Cellar";
export HOMEBREW_REPOSITORY="/usr/local/Homebrew";
export PATH="/usr/local/bin:/usr/local/sbin${PATH+:$PATH}";
export MANPATH="/usr/local/share/man${MANPATH+:$MANPATH}:";
export INFOPATH="/usr/local/share/info:${INFOPATH:-}";
```

**Comment by wangliang1989** [comment]
![image](https://user-images.githubusercontent.com/12059719/114119703-c26da900-991d-11eb-9ffc-71599194d910.png)

**Comment by wangliang1989** [comment]
那个教程说的也不一定对

**Comment by seisman** [comment]
@core-man I think we can close the issue.

**Comment by core-man** [comment]
按照以上对，@wangliang1989 安装 ARM 下的 Homebrew 时候并没有额外操作，直接按照教程执行即可，对吗？

**Comment by wangliang1989** [comment]
我现在的观点是如果没有网络问题，只要按照brew官方的做法，执行那一句命令就行。我现在把关于brew的环境变量都注释了，没有发现有问题。
我之前自己是实现了终端里正常上网的，但是我也出现了网络问题，目前看问题是当下载文件不是从brew，二是从软件相应的官方站点下载的时候，流量会是直连。如果网卡设置为全局走正常渠道，就不会有问题。

**Comment by wangliang1989** [comment]
我在开始装M1的时候那几天，有些蒙，因为我买的线材没到，当时我屏幕的显示不正常，看不清楚
