### ISSUE TITLE
Remove vim?

### ISSUE THREAD

**Issue by seisman** [seismo-learn/seismology101#290]
Do you think we can remove the whole section about vim, since vscode can be used anywhere now.

**Comment by core-man** [comment]
No, I don't think so. Although we use VS Code to do coding jobs most time, I feel new babies should know some basics of vim. Sometimes, it is convenient to just vim to do some quick edit. To be honest, I use vim every day to check the file and do some tiny revisions.

BTW, the current content is very limited and I guess it may only take less than 10 minutes.

**Comment by seisman** [comment]
We use vim only because it's the first text editor we learned, and we're getting used to it.

For new users, vim has a very high learning curve. The current short material won't help much, because newbies even don't know how to check the current vim mode (normal mode or edit mode).

**Comment by seisman** [comment]
BTW, we can finish the vim tutorial in 10 minutes, because we already know vim well. However, for most people, that's not the case.

**Comment by core-man** [comment]
> BTW, we can finish the vim tutorial in 10 minutes, because we already know vim well. However, for most people, that's not the case.

Let's keep the vim tutorial for some time and wait. If we could organize some tutorials in the future, some feedback could come from new babies. Meanwhile, how about keeping this issue open until we get enough feedback from new babies?

**Comment by seisman** [comment]
OK.
