### ISSUE TITLE
Instructions to give feedback

### ISSUE THREAD

**Issue by seisman** [seismo-learn/seismology101#293]
After reading the landing page (https://seismo-learn.org/seismology101/), it's still unclear how to give feedbacks.

**Comment by core-man** [comment]
Let's add How can I talk to you, like https://github.com/GenericMappingTools/pygmt/blob/master/CONTRIBUTING.md#how-can-i-talk-to-you.

**Comment by seisman** [comment]
Perhaps we should just add a link to https://github.com/seismo-learn/seismology101/discussions?

**Comment by core-man** [comment]
We have three ways for contributors to contribute to seismo-learn (https://seismo-learn.org/contributing/general-guidelines/):

> - 修改文档源码并提交 Pull Request（不熟悉 Pull Request 的读者可以参考 Pull Request 流程）
> - 在 GitHub 上的文档源码仓库下提交 Issue
> - 在 GitHub 上的文档源码仓库下的 Discussions 上留言（也可以直接点击文档网页左下角的“参与讨论”）

We may have such a list on the landing page:
> - 在 GitHub 上的文档源码仓库下的 Discussions 上留言（也可以直接点击文档网页左下角的“参与讨论”）
> - 修改文档源码并提交 Pull Request（不熟悉 Pull Request 的读者可以参考 Pull Request 流程）
> - 在 GitHub 上的文档源码仓库下提交 Issue
