### ISSUE TITLE
Add seismic data fetch manuals

### ISSUE THREAD

**Issue by core-man** [seismo-learn/seismology101#308]
Shall we maintain complete seismic data fetch guides? See https://seisman.github.io/SAC_Docs_zh/appendix/data-fetch/#

If so, shall we do it in `seismology101` or `seismology`? Meanwhile, we could remove that section in SAC_docs if we'd like to maintain it in seismo-learn.

**Comment by core-man** [comment]
close it?

**Comment by seisman** [comment]
I think we should have a summary page in seismology101 and complete manuals in software.

**Comment by core-man** [comment]
> I think we should have a summary page in seismology101 and complete manuals in software.

sounds good to me.

**Comment by seisman** [comment]
I think we can close the issue now as we already have a section https://seismo-learn.org/seismology101/exercises/waveform/#id8 for it.
