### ISSUE TITLE
没有教怎么下文献

### ISSUE THREAD

**Issue by wangliang1989** [seismo-learn/seismology101#322]
没有教怎么下文献，要不加一个？

**Comment by core-man** [comment]
#30 里有一个有关 scientific reading 的计划小节，下载文献是其中的一小部分内容。
- journal booking
- paper searching
- paper management
- reading methods

现在还没时间开始整理和撰写这一块内容。

**Comment by core-man** [comment]
close this issue since we have this plan in #30 ?
