### ISSUE TITLE
Add a note in OS setup

### ISSUE THREAD

**Issue by core-man** [seismo-learn/seismology101#323]
I feel that new babies could think they have to install all the software for their OS. Actually, they only need to install the system, and all the other softeware can be installed later when they need to use them. This will save their time to read the tutorials.

**Comment by core-man** [comment]
Ping @seisman @wangliang1989 for comment

**Comment by wangliang1989** [comment]
很有可能

**Comment by seisman** [comment]
Sounds OK to me.
