### ISSUE TITLE
MacOS的配置指南是否可以添加brew安装软件后的环境变量提示

### ISSUE THREAD

**Issue by wangliang1989** [seismo-learn/seismology101#332]
brew安装一些软件后，会提示对环境变量进行修改，例如：
````
If you need to have openjdk first in your PATH, run:
  echo 'export PATH="/opt/homebrew/opt/openjdk/bin:$PATH"' >> ~/.zshrc

For compilers to find openjdk you may need to set:
  export CPPFLAGS="-I/opt/homebrew/opt/openjdk/include"
````
是否可以考虑在文档中说明第二个环境变量的含义。因为如果不知情加了第二个环境变量，似乎以后编译啥软件，都会在编译命令后加入相关参数。

**Comment by core-man** [comment]
这个只与macOS安装 Java 运行环境有关，目前教程只有安装命令，并没有告诉读者修改环境变量。因为seis101面向的是初级用户，新手一般会基本按照流程走，并不会进行额外操作。如果这两个环境变量并不需要修改，我觉得就没有必要加说明。如果需要修改，那可以加个note。

**Comment by wangliang1989** [comment]
我最开始以为两个都要加，后来编译不想干的东西的时候，会出现那个特别的编译选项，才意识到一般情况第二个不加。你这么一说，我试验了下，似乎第一个环境变量也不需要加。不过我还没重启系统，似乎现在的source命令对环境变量只做加法不做减法

**Comment by core-man** [comment]
我都没有加，TauP是可以用的。

**Comment by seisman** [comment]
> 是否可以考虑在文档中说明第二个环境变量的含义。因为如果不知情加了第二个环境变量，似乎以后编译啥软件，都会在编译命令后加入相关参数。

相关内容会在 https://seismo-learn.org/seismology101/programming/compile/ 介绍。

> 不过我们是否有必要在安装一开始加个note，告诉读者一般只需要按照教程操作，并不需要进行额外操作，类似java运行环境安装提示的这些额外操作。

我感觉这只会造成额外的困惑。

**Comment by core-man** [comment]
那这个issue貌似就没啥好做了？

**Comment by core-man** [comment]
close this issue? we would work on it in #192.
