### ISSUE TITLE
Move x-server in WSL setup to dropdown box

### ISSUE THREAD

**Issue by core-man** [seismo-learn/seismology101#346]
See https://seismo-learn.org/seismology101/computer/wsl-setup/#x-server. Do most WSL users have to install x-server? If not, shall we move it into a dropdown box? Ping @zhaozhiyuan1989 @seisman for comments.

**Comment by seisman** [comment]
I believe yes if you want to use SAC, TauP or even plotting using matplotlib.

**Comment by core-man** [comment]
> I believe yes if you want to use SAC, TauP or even plotting using matplotlib.

You mean yes for `Do most WSL users have to install x-server? `?

**Comment by seisman** [comment]
> Do most WSL users have to install x-server?

Yes.
