### ISSUE TITLE
Add a recommend label for each software in OS setup

### ISSUE THREAD

**Issue by core-man** [seismo-learn/seismology101#352]
As a new baby, I still don't know which software is needed and recommended although there is a note at the top of each OS setup. Shall we add a **recommended** label or other name/way for each software?

**Comment by seisman** [comment]
Why not just install them all? They're all easy to install, no?

**Comment by core-man** [comment]
> Why not just install them all?  They're all easy to install, no?

Yes, they are easy to install. But new babies can come back to install them after they read all the tutorials. Most of the software are not needed at all for them to read the tutorials. I agree that the new babies should install them most if not all.

**Comment by seisman** [comment]
> install them after they read all the tutorials

Do you mean `tldr` or `ack`?

**Comment by core-man** [comment]
> > install them after they read all the tutorials
> 
> Do you mean `tldr` or `ack`?

also wps, Google Earth, Google Chrome

**Comment by seisman** [comment]
> also wps, Google Earth, Google Chrome

I believe users know what they are and if they need them.

**Comment by core-man** [comment]
> > also wps, Google Earth, Google Chrome
> 
> I believe users know what they are and if they need them.

we are talking to new babies, right? they know them?

**Comment by seisman** [comment]
Of course!

**Comment by core-man** [comment]
> Of course!

or we may add a label to some software to indicate they may choose to install them depending on their own perfection? e.g., those we listed above

**Comment by core-man** [comment]
For us, it's okay to decide which one is prefered. Do you think new babies have to install all of them?

**Comment by seisman** [comment]
Still, I don't think we need to add any labels for each software. All the software listed is useful and that's exactly why we recommend them. For each software, we already provide the link to the homepage, users can click the link and read more about it to decide if they want to install it. For newbies who know nothing, they should install all of them.
