### ISSUE TITLE
Add some cards for each sections on the landing page?

### ISSUE THREAD

**Issue by core-man** [seismo-learn/seismology101#353]
We have so many sections at the sidebar, and maybe more in the future. It may be better to add some cards for each chapter on the landing page. See https://docs.generic-mapping-tools.org/latest/.

**Comment by seisman** [comment]
Perhaps not necessary, because we expect readers to read the tutorial from the beginning to the end. 

It's also easy to scroll down the TOC in the left sidebar to view all sections.
