### ISSUE TITLE
centos如何安装oneapi

### ISSUE THREAD

**Issue by wangliang1989** [seismo-learn/seismology101#355]
Centos上如何安装one api？如果之前已经安装 ifor，现在已经过期，能不能做一个小修改，继续用呢？

**Comment by seisman** [comment]
centos 与 fedora 相同

**Comment by core-man** [comment]
直接按照 Fedora 的教程安装即可。我目前是 CentOS (7.5) ，安装和使用没有遇到问题。

**Comment by wangliang1989** [comment]
![image](https://user-images.githubusercontent.com/12059719/123020659-3986e980-d405-11eb-9a37-842342d7d669.png)
我现在Linux上不了网
脱机是在这里下载吗？我在这里没有看见ifor
https://software.intel.com/content/www/us/en/develop/tools/oneapi/base-toolkit/download.html?operatingsystem=linux&distributions=webdownload&options=offline

**Comment by core-man** [comment]
ifor是指ifort吗？

**Comment by wangliang1989** [comment]
就是intel fortran

**Comment by core-man** [comment]
在 HPC Toolkit 里

**Comment by wangliang1989** [comment]
其实我机器里现在有intel fortran，但是是去年装的一年授权那种

**Comment by core-man** [comment]
> 其实我机器里现在有intel fortran，但是是去年装的一年授权那种

现在已经找不到之前授权那种了，我也没摸索如何使用老的。one api不需要授权了，都可以使用。
