### ISSUE TITLE
Optimize images in PRs automatically

### ISSUE THREAD

**Issue by seisman** [seismo-learn/seismology101#358]
This action looks useful: https://github.com/marketplace/actions/image-actions

**Comment by core-man** [comment]
A question: see https://github.com/gmt-china/GMT_docs/blob/master/ci/image_optimize.sh. so we optimize figures using the bash script in GMT_docs?

**Comment by seisman** [comment]
The script was used before we migrated the CI service from Travis to GitHub Actions. 

The GMT_Docs repository cannot use the image-actions because most of the images in the GMT_Docs are generated by the `gmtplot` directive. Thus, these images are not added in the repository and image-actions won't optimize them.
