### ISSUE TITLE
Intel Fortran compiler

### ISSUE THREAD

**Issue by core-man** [seismo-learn/seismology101#361]
See https://software.intel.com/content/www/us/en/develop/articles/oneapi-standalone-components.html#fortran. It seems that we could install a single Intel Fortran compiler instead of OneAPI-HPC.

**Comment by seisman** [comment]
Yes, but it seems that the installation method is totally different from installing OneAPI, but looks more difficult to explain.

**Comment by seisman** [comment]
Close?

**Comment by core-man** [comment]
Shall we add a note for this link in OneAPI installation because OneAPI could be a little larger if someone only want intel Fortran compile.
