### ISSUE TITLE
Setup guides for Fedora 34/35 

### ISSUE THREAD

**Issue by seisman** [seismo-learn/seismology101#367]
The setup guides for Fedora is still using Fedora 33, but the latest Fedora release is Fedora 34 (released in April 2021) and Fedora 35 will be released in October 2021.

We need to update the setup guides for Fedora 35 after it is released. 

Since Fedora has a semiannual release cycle, which is too fast, I believe we don't want to bother tracking the latest releases. Thus, we need to add a warning that "The setup guide is targeted for Fedora XX, which may not be the latest release. You can find the latest Fedora release at XXX, and please help update setup guide if any material is out-of-date".

**Comment by core-man** [comment]
Yes to me~

**Comment by seisman** [comment]
FYI, Fedora was released on Nov. 2, 2021 and we will give it a try today or in the next few days.

**Comment by core-man** [comment]
Shall we add notes about gnome extensions (Application, Places, Floating Dock, etc) and tweaks?

```
sudo dnf install gnome-extensions-app
sudo dnf install tweaks
```

**Comment by seisman** [comment]
We should install `java-11-opendjk` on Fedora.

**Comment by seisman** [comment]
> Shall we add notes about gnome extensions (Application, Places, Floating Dock, etc) and tweaks?
> 
> ```
> sudo dnf install gnome-extensions-app
> sudo dnf install tweaks
> ```

Do we still need to add notes for these packages?

**Comment by core-man** [comment]
> > Shall we add notes about gnome extensions (Application, Places, Floating Dock, etc) and tweaks?
> > ```
> > sudo dnf install gnome-extensions-app
> > sudo dnf install tweaks
> > ```
> 
> Do we still need to add notes for these packages?

I think we could add them at the end so that new babies know how to adjust their appearance.

**Comment by seisman** [comment]
> > > Shall we add notes about gnome extensions (Application, Places, Floating Dock, etc) and tweaks?
> > > ```
> > > sudo dnf install gnome-extensions-app
> > > sudo dnf install tweaks
> > > ```
> > 
> > 
> > Do we still need to add notes for these packages?
> 
> I think we could add them at the end so that new babies know how to adjust their appearance.

I'm going to close the issue because people have different flavors about the appearance of their GNOME desktop, especially for people who have never used the old GNOME.
