### ISSUE TITLE
Break the "backup" section into seperate pages

### ISSUE THREAD

**Issue by seisman** [seismo-learn/seismology101#387]
https://seismo-learn.org/seismology101/best-practices/backup/

Linux users don't care about how to back up the macOS system, so it would be better to break the long section into multiple pages:

#. An introduction page explaining why backup is important
#. how to backup on Linux
#. how to backup on macOS
#. how to backup on Windows

Since `rsync` can be used on both Linux and macOS, we should include the `rsync` method in both operating systems.

Let's discuss this before working on it.

**Comment by core-man** [comment]
Sound good to me. We could have a single file for the `rsync` command, and include it in both Linux and macOS?

**Comment by seisman** [comment]
> Sound good to me. We could have a single file for the `rsync` command, and include it in both Linux and macOS?

Yes.
