### ISSUE TITLE
Switch from sphinx-panels to sphinx-design

### ISSUE THREAD

**Issue by seisman** [seismo-learn/seismology101#391]
We're trying to switch to the sphinx-book-theme (https://github.com/seismo-learn/seismology101/pull/153). However, the theme doesn't work well with the sphinx-panels extension.

It turns out the developers are planning to deprecate the sphinx-panels extension and sphinx-design will be the replacement (https://github.com/executablebooks/sphinx-panels/issues/67).

We may want to switch from sphinx-panels to sphinx-design (https://sphinx-design.readthedocs.io/en/latest/).

**Comment by core-man** [comment]
Look great. It seems that `sphinx-design` is easier to use.
