### ISSUE TITLE
Consistent path for our own codes and scripts.

### ISSUE THREAD

**Issue by core-man** [seismo-learn/seismology101#40]
It's better to separate our own codes with others' codes in `~/src`.

How about `~/codes/` and `~/scripts/` ?

See a related issue https://github.com/seismo-learn/software/issues/108.

**Comment by seisman** [comment]
Scripts are also codes, so what are the differences?

**Comment by core-man** [comment]
> Scripts are also codes, so what are the differences?

I usually put C and Fortran codes in `~/codes` and bash, Perl, Python scripts in `~/scripts`.

For example, the content of my `~/scripts` is now:

- `pkgs_perl`: my own Perl packages that are commonly used by my scripts.
- `pkgs_python`: my own Python packages that are commonly used by my scripts.
- `SeisScripts`: some commonly used seismic scripts or templates
- `SOD.recipes`: SOD recipes.

I agree these two are the same. Maybe can be put together. Codes or scripts should be project-oriented.

**Comment by seisman** [comment]
I don't think it's a good practice to group codes by programming languages, especially for scripts. For standalone scripts, do you really care about if the codes are written in bash, Perl or Python? For scripts that you want to call in other scripts, I think it's better to write a separate package, right? I believe most seismologists have a seispy package for their own use.

**Comment by seisman** [comment]
For most projects, I usually put the project-specific codes in the project's bin, src or scripts directory. If the codes or scripts are more general and can be used in many other projects, then it's time to move the codes outside the project directory.

**Comment by core-man** [comment]
> For most projects, I usually put the project-specific codes in the project's bin, src or scripts directory. If the codes or scripts are more general and can be used in many other projects, then it's time to move the codes outside the project directory.

Yes, that's just what I do. The codes and scripts in `~/codes/` are common-usely source codes, e.g., `double difference location codes`.

> I don't think it's a good practice to group codes by programming languages, especially for scripts. For standalone scripts, do you really care about if the codes are written in bash, Perl or Python? For scripts that you want to call in other scripts, I think it's better to write a separate package, right? I believe most seismologists have a seispy package for their own use.

Yes, so we will put `seispy` in `~/codes`. This is my question.

**Comment by seisman** [comment]
To me, `~/codes` is enough.

**Comment by core-man** [comment]
> To me, `~/codes` is enough.

Yes.

**Comment by core-man** [comment]
**A brief summary:**

For most projects, put the project-specific codes in the project's bin, src or scripts directory

If the codes are more general and can be used in many other projects, then we can move the codes outside the project directory and and put it in `~/codes/`.

**Comment by seisman** [comment]
Closing. See https://github.com/seismo-learn/seismology101/issues/42 for further discussions.
