### ISSUE TITLE
Strategy  to include Jupyter notebooks in Sphinx documentation

### ISSUE THREAD

**Issue by seisman** [seismo-learn/seismology101#412]
In the "exercises" chapter, we plan to write some tutorials about downloading and processing seismic data, mainly using ObsPy. As ObsPy is written in Python, Jupyter notebooks are the most appropriate way to write these tutorials.

For people who know little about Notebooks, Notebooks are documents that can contain both Python codes and rich text elements (e.g., markdown and math equations). The Python codes in notebooks can be run in Jupyter and the results (outputs and images) can also be included in the notebooks.

The question is: how to include Jupytere notebooks in our Sphinx documentation? See https://docs.readthedocs.io/en/stable/guides/jupyter.html for very good summary material. It turns out there are multiple ways to include notebooks in Sphinx documentation and each one has some pros and cons. We must make some choices. Here are the available options:

### Option 1: Include both codes and outputs in notebooks 

What we need to do:

1. Write Python codes and markdown texts in notebooks (`.ipynb` files)
2. Run the notebooks locally and store the results in the same notebooks
3. Commit the `.ipynb` files that have both inputs and outputs

Either [`nbsphinx`](https://nbsphinx.readthedocs.io/) or [`myst-nb`](https://myst-nb.readthedocs.io/) can parse `.ipynb` files and convert them to HTML files. PR #409 is an example using `myst-nb`.

**Pros:**

1. No need to install ObsPy and other potential packages in GitHub Actions

**Cons:**

1. Notebooks are JSON files. When we make changes and submit PRs, the diffs are not easy to read, thus making the PR review more difficult
2. Outputs are stored in notebooks, thus the file sizes are large, especially when notebooks contain image outputs. When we make changes to the plotting codes, the image will also change, thus increasing the git repository size significantly.

### Option 2: Only include codes in notebooks

It's also possible to only include codes in notebooks, let the GitHub Actions server run the notebooks, and generate HTML files that show both inputs and outputs. 

PR #341 is an example using `nbsphinx`, and PR #411 is an example using `myst-nb`.

**Pros**

1. Outputs are NOT stored in notebooks, thus the file size and git repository size will be much smaller compared to option 1.

**Cons**

1. Need to install ObsPy and other potential packages on the GitHub Actions, thus slower. For reference, the current workflow in the main branch takes ~15 s to install packages (using pip), while the workflow in PR #411 takes about 90s (using conda). 
2. Running the notebooks also take some time. For the small notebook in PR #411, building the documentation takes 6 s without notebooks and 9 s with notebooks. After we have more notebooks, especially those that download seismic waveform data and perform complicated data processings, I expect building the documentation will be much slower (hopefully less than 10 minutes).

Luckily, the `myst-nb` extension can [cache notebook outputs](https://myst-nb.readthedocs.io/en/latest/use/execute.html). As I understand it, it means that a notebook won't be re-executed if it's not changed, thus can saving time. In PR #411, the notebook outputs are cached in GitHub Actions. Thus, changing other files won't re-execute the notebook.

If we decide to choose this option, I believe `myst-nb` is better than `nbsphinx`, because `myst-nb` allows caching.

### Option 3: Write codes in markdown

If we agree that option 2 is better, then we may want to write codes in markdown rather than notebooks. The main reason is, notebooks are written in JSON (see this [example ipynb file](https://github.com/seismo-learn/seismology101/pull/411/files#diff-f64d091ecb3b812b0642f1e7878544c9b3da33c252eeddce3920655c4a2f0dc1), thus it's not as readable as plain-text markdown files.

`myst-nb` allows writing notebooks in markdown syntax (it's called myst markdown syntax). The tool `jupytext` can convert jupyter notebooks to myst markdown and vice versa.  

PR #413 is an example showing how myst-nb works with markdown files. The markdown file for the distaz notebook is converted by running `jupytext distaz.ipynb --to myst`. But, it's also possible to let JupyterLab save both `.ipynb` and `.md` files when editing `.ipynb` files (see https://github.com/mwouts/jupytext#paired-notebooks).

**Pros**

1. Compared to `.ipynb` files, markdown files are more readable, diff-able, and also smaller.
2. myst markdown has some cool features such as [hiding cell contents](https://myst-nb.readthedocs.io/en/latest/use/hiding.html), while notebooks don't
3. As markdown files are small, it's easy to migrate all markdown files to notebooks (option 1) if we realize that running notebooks are too slow

**Cons**

Maybe no?

**Comment by core-man** [comment]
Currently, I have one question: If we choose option 2 or 3, we need to re-build all the notebooks regularly, because the exercises might not work (e.g., some packages are updated) while Sphinx can still get output from the cache. We can either manually update the notebooks (e.g., update package version) or set a regular re-build workflow.

BTW, if we use myst markdown, we can use `jupytext` to convert between `.ipynb` files and `MyST-markdown` files (https://myst-nb.readthedocs.io/en/latest/use/markdown.html#convert-between-ipynb-and-myst-notebooks):

> To convert .ipynb to MyST-markdown, run: `jupytext notebook.ipynb --to myst`
> To convert MyST-markdown to .ipynb, run: `jupytext mystfile.md --to ipynb`

**Comment by seisman** [comment]
We have decided to adopt option 3 as in #413. Closing this issue.
