### ISSUE TITLE
Best practices for file managements

### ISSUE THREAD

**Issue by seisman** [seismo-learn/seismology101#42]
We need to update this post https://blog.seisman.info/file-organization/.

Standard home subdirectories for most Linux distros:

- `Documents`
- `Downloads`
- `Videos`
- `Music`
- `Desktop`

What we already decide:

- `~/bin`
- `~/src`
- `~/software`
- `~/opt`
- `~/projects`
- `~/codes`

Others?

**Comment by core-man** [comment]
- data: some commonly-used dataset, e.g., catalog, dcw-gmt, gshhg-gmt, crust2.0, fault dataset. I also some setting notes in this dir.
- Trash: I usually move some files in this dir and then delete them.
- workspace: a temporal dir I do some stuff. e.g., some coures jupynotebook, gmt, fortran
