### ISSUE TITLE
Better way to install VS Code on Fedora

### ISSUE THREAD

**Issue by seisman** [seismo-learn/seismology101#432]
This is the recommended way on the VS Code website (https://code.visualstudio.com/docs/setup/linux#_rhel-fedora-and-centos-based-distributions): 
```
sudo rpm --import https://packages.microsoft.com/keys/microsoft.asc
sudo sh -c 'echo -e "[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" > /etc/yum.repos.d/vscode.repo'
dnf check-update
sudo dnf install code
```

It writes a repository file to the `/etc/yum.repos.d` directory and installs vscode, which is slow but still acceptable. However, because the vscode repository is enabled by default, anytime you run a `dnf update` or `dnf install xxx` command, dnf will try to update the package metadata from all repositories (including the vscode repository). It makes `dnf` extremely slow.

We can manually edit `/etc/yum.repos.d/vscode.repo` and change `enabled=1` to `enabled=0` to disable the repository. But we won't be able to get any vscode updates.

**Comment by seisman** [comment]
For users in China, they should download the RPM tarball, and double click it to install it. In this way, no repo file will be added to the `/etc/yum.repos.d` directory.

**Comment by core-man** [comment]
> For users in China, they should download the RPM tarball, and double click it to install it. In this way, no repo file will be added to the `/etc/yum.repos.d` directory.

sound good.
