### ISSUE TITLE
Replace anaconda with miniconda

### ISSUE THREAD

**Issue by core-man** [seismo-learn/seismology101#439]
Anaconda contains a lot of packages that we don't use in daily researches. It makes package installation too slow, including itself. Instead, miniconda installation is very fast (maybe tens of seconds). It's almost the same to install miniconda as compared to anaconda. Therefore, we may want new babies to use miniconda to save a lot of time.

Anaconda | Miniconda
---|---
slow installation | very fast installation
lots of packages installed with most of them unnecessary  | only a few packages installed
self-updating IS allowed but slow | self-updating IS NOT allowed
slow package installation | faster package installation

**Comment by seisman** [comment]
Agreed.

**Comment by seisman** [comment]
[`mamba`](https://github.com/mamba-org/mamba) is much faster than `conda`. 

Now mamba works well for me. You may want to give it a try. To try it, run:
```
$ conda install mamba
$ mamba install obspy
```
