### ISSUE TITLE
Provide step-by-step screenshots for setting up a bootable USB driver

### ISSUE THREAD

**Issue by seisman** [seismo-learn/seismology101#453]
In the Fedora setup guides (https://seismo-learn.org/seismology101/computer/fedora-setup/#usb), we recommend setting up a bootable USB driver using Ventory and providing the link to the [official documentation](https://ventoy.net/cn/doc_start.html). However, I feel that the official documentation is a little too long, especially for users who have never used it.

I think it would be better if we can provide step-by-step screenshots showing how to use ventory (similar to the guide (https://techz.io/how-to-install-fedora/) for installing Fedora).

We can use the [card-carousel](https://sphinx-design.readthedocs.io/en/latest/cards.html#card-carousels) to display multiple screenshots, without making the page too long to read.

**Comment by core-man** [comment]
Sounds great~

**Comment by seisman** [comment]
BTW, ventory can be used on both Windows and Linux. I bet that most users have a Windows machine, so the step-by-step instructions should be done on a Windows machine.
