### ISSUE TITLE
Add PR labelers

### ISSUE THREAD

**Issue by core-man** [seismo-learn/seismology101#46]
Do we want to label PRs similar to https://github.com/seismo-learn/software/issues/72.

- computer
- programming
- seismology
- exercise
- practise

**Comment by seisman** [comment]
It seems unnecessary to me. Labeling makes it easier for us to find related PRs and issues. It's useful for software as we make changes from time to time. 

But for documentation like seismology and seismology101, I don't think we care about the commit history.

**Comment by seisman** [comment]
> But for documentation like seismology and seismology101, I don't think we care about the commit history.

For documentation, the latest is always the best one, but that's not true for software.

**Comment by core-man** [comment]
okay
