### ISSUE TITLE
Add a tutorial for Python

### ISSUE THREAD

**Issue by seisman** [seismo-learn/seismology101#469]
Possible content for the Python tutorial:

1. Introduce Anaconda and install it
2. Write a simple Python script in VSCode and explain what a Python script looks like
3. How to run a Python script in a terminal or directly in vscode
4. Introduce Jupyter Notebook, because it's popular and powerful
5. Introduce a few packages, like numpy, scipy and matplotlib and show a few examples.
6. How to install packages? mamba, conda, and pip
7. Provide more learning resources.

Related to https://github.com/seismo-learn/seismology101/issues/69.

**Comment by seisman** [comment]
Both [JupyterLab](https://jupyter.org/) and VSCode (https://code.visualstudio.com/docs/datascience/jupyter-notebooks) can execute notebooks. Which one should we introduce in the tutorial?

**Comment by core-man** [comment]
Maybe JupyterLab is better as we'd like to recommend it in daily research work, no?

**Comment by seisman** [comment]
I've tried to write notebooks in vscode recently, and find that it works similarly to JupyterLab, but vscode's auto-completion is much faster and better.

**Comment by seisman** [comment]
Let's use JupyterLab first and determine which one is better later.

**Comment by seisman** [comment]
I'm reopening the issue because I think some of the Python learning resources are too long for beginners and we should list some introductory materials instead.
