### ISSUE TITLE
Add exercises for downloading earthquake catalog

### ISSUE THREAD

**Issue by seisman** [seismo-learn/seismology101#549]
Originally proposed in https://github.com/seismo-learn/seismology101/issues/205:

- [ ] How to search and download the earthquake catalog
- [ ] Catalog I/O or format conversion
- [ ] Plot earthquake locations: map view and cross-section

**Comment by seisman** [comment]
Ideas of the structure of this section:

- [ ] Show how to select and display earthquakes in [wilber](https://ds.iris.edu/wilber3/find_event). Strictly speaking, wilber is a tool to request seismic data, but I think it's still a very useful visual tool to quickly select and view earthquakes.
- [ ] Show to download earthquake catalog using ObsPy's [Client.get_events() function](https://docs.obspy.org/packages/autogen/obspy.clients.fdsn.client.Client.get_events.html)
- [ ] Plotting earthquake catalog in map view
- [ ] Plotting earthquake catalog in cross section view (low priority)

> * Catalog I/O or format conversion

As for catalog format conversion, I don't think we need to talk about it, because there are too many formats for earthquake catalog. Instead, we can show how to convert ObsPy's catalog (actually QuakeML format) into a simple text file with a few columns: origin time, longitude, latitude, depth, magnitude. It's the simplest catalog format and is very commonly used.

**Comment by seisman** [comment]
> * Show how to select and display earthquakes in [wilber](https://ds.iris.edu/wilber3/find_event). Strictly speaking, wilber is a tool to request seismic data, but I think it's still a very useful visual tool to quickly select and view earthquakes.

FYI, I've changed my mind, and I think we should use https://earthquake.usgs.gov/earthquakes/search/ instead.

**Comment by core-man** [comment]
> > * Show how to select and display earthquakes in [wilber](https://ds.iris.edu/wilber3/find_event). Strictly speaking, wilber is a tool to request seismic data, but I think it's still a very useful visual tool to quickly select and view earthquakes.
> 
> FYI, I've changed my mind, and I think we should use https://earthquake.usgs.gov/earthquakes/search/ instead.

Sounds good to me~
