### ISSUE TITLE
Best practices for zsh

### ISSUE THREAD

**Issue by seisman** [seismo-learn/seismology101#61]
- [x] introduction to zsh
- [ ] Two popular zsh frameworks:
  - [x] [oh-my-zsh](https://github.com/ohmyzsh/ohmyzsh)
  - [ ] [prezto](https://github.com/sorin-ionescu/prezto)

**references**
- https://sourabhbajaj.com/mac-setup/iTerm/zsh.html

**Comment by seisman** [comment]
[oh-my-zsh](https://github.com/ohmyzsh/ohmyzsh) and [prezto](https://github.com/sorin-ionescu/prezto) are the two popular zsh framework.

**Comment by core-man** [comment]
how about prezto？

**Comment by seisman** [comment]
prezto is just another framework. I don't think we should introduce both.

**Comment by core-man** [comment]
okay. I think oh my zsh is enough.
