### ISSUE TITLE
Fedora setups

### ISSUE THREAD

**Issue by seisman** [seismo-learn/seismology101#63]
We need volunteers working on the guide of setting up Fedora.

See https://seismo-learn.org/seismology101/computer/fedora-setup/

**Comment by core-man** [comment]
How someone on GitHub will see the labeler and come?

**Comment by seisman** [comment]
Someone who visits the issue page may look for something he/she can help. Those "help wanted" issues may be the one they want to do.

**Comment by seisman** [comment]
I may write the Fedora setup instructions using a virtual machine.
