### ISSUE TITLE
Ubuntu setup

### ISSUE THREAD

**Issue by seisman** [seismo-learn/seismology101#64]
We recommend using Fedora based on our own tastes, but Ubuntu is still one of the most popular Linux distros. It would be good if someone volunteers to write a guide to setup Ubuntu.

See https://seismo-learn.org/seismology101/computer/fedora-setup/ for references.

**Comment by core-man** [comment]
I may write the Ubuntu setup instructions using both a virtual machine and a Ubuntu machine.
