### ISSUE TITLE
WSL setup 

### ISSUE THREAD

**Issue by seisman** [seismo-learn/seismology101#65]
As per the feedback from @zhaozhiyuan1989, the Microsoft official documentation [English version](https://docs.microsoft.com/en-us/windows/wsl/install-win10) and [Chinese version](https://docs.microsoft.com/zh-cn/windows/wsl/install-win10) are pretty clear. 

So, for setting up WSL, it's pretty easy:

1. Follow the official guide
2. Install Ubuntu or other Linux distros (Fedora is not available)
3. Setting up Ubuntu following #64 
4. May need to install something for Xserver #81 
5. Maybe add some notes about the differences between Linux and WSL (I don't know, maybe paths are slightly different).

**Comment by core-man** [comment]
> 4. May need to install something for Xserver

Yes, e.g., `VcXsrv`.

See http://www.yuan-ji.me/%E5%A6%82%E4%BD%95%E5%9C%A8Windows-Subsystem-for-Linux-(WSL)-%E4%B8%8A%E8%BF%90%E8%A1%8CLinux-GUI-%E8%BD%AF%E4%BB%B6/
