### ISSUE TITLE
Issue on page /computer/fedora-setup.html

### ISSUE THREAD

**Issue by wangliang1989** [seismo-learn/seismology101#669]
制作安装盘的工具为何不直接使用fedora官方提供的版本？

**Comment by seisman** [comment]
1. 为了 Fedora 和 Ubuntu 都使用相同的安装盘制作工具，简化教程的维护难度
2. Ventoy 用起来很简单，而且可以把一个 U 盘制作成多个系统的启动盘

**Comment by wangliang1989** [comment]
Ventoy 支持 Mac？

**Comment by seisman** [comment]
只支持 Windows 和 Linux.

**Comment by wangliang1989** [comment]
所以不改？

**Comment by seisman** [comment]
哪里需要改？

**Comment by wangliang1989** [comment]
应该优先使用官方的推荐

**Comment by seisman** [comment]
1. Fedora 推荐 Fedora Media Writer，但是 Ubuntu 官方并没有推荐，所以对于整个 Linux 系统而言，不存在所谓的官方推荐。
2. Ventoy 比 Fedora Media Writer 功能更强大
