### ISSUE TITLE
Add authors/contributors to the landing page?

### ISSUE THREAD

**Issue by seisman** [seismo-learn/seismology101#685]
Currently, we only mention the "seismo-learn team" on the landing page (https://seismo-learn.org/seismology101/), i.e., 

<img width="471" alt="image" src="https://github.com/seismo-learn/seismology101/assets/3974108/aedab994-dfde-4b51-bcf1-df0ee25d7c85">

I'm thinking about adding more details about the "authors"/"maintainers". Maybe we should add a team gallery to the landing page, like https://www.pygmt.org/dev/team.html or https://github.com/all-contributors/all-contributors#contributors-

**Comment by seisman** [comment]
Ping @core-man for thoughts.

**Comment by core-man** [comment]
> https://github.com/all-contributors/all-contributors#contributors-

Sounds good. We could also use "founder", "maintainer" and "contributor".

**Comment by seisman** [comment]
Closed by #687
