### ISSUE TITLE
Tutorials for programming languages

### ISSUE THREAD

**Issue by seisman** [seismo-learn/seismology101#69]
- [ ] Bash
  - https://learnxinyminutes.com/docs/zh-cn/bash-cn/
  - https://101.lug.ustc.edu.cn/Ch06/#shell-scripts
  - http://www.ruanyifeng.com/blog/2020/04/bash-tutorial.html
  - https://www.bookstack.cn/read/bash-tutorial/README.md
  - https://docs.gmt-china.org/latest/tutorial/scripting/#bash
  - http://billie66.github.io/TLCL/book/index.html: 编写 Shell 脚本
  - https://www.tutorialspoint.com/unix/shell_scripting.htm
  - https://missing-semester-cn.github.io/2020/shell-tools/

- [ ] Python
  - https://learnxinyminutes.com/docs/zh-cn/python-cn/
  - https://101.lug.ustc.edu.cn/Ch07/#py
  - recommand IPython, jupyter-notebook, jupyterlab, PyCharm

- [ ] C
  - https://learnxinyminutes.com/docs/zh-cn/c-cn/
  - https://101.lug.ustc.edu.cn/Ch07/#c

- [ ] Fortran
  - https://learnxinyminutes.com/docs/zh-cn/fortran95-cn/
  - https://fortran-lang.org/learn/quickstart

- [x] Markdown
  - https://help.coding.net/docs/management/markdown.html
  - https://guides.github.com/features/mastering-markdown/
  - https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet
  - https://dillinger.io/
  - https://missing-semester-cn.github.io/2020/potpourri/#markdown
  - https://commonmark.org/help/

**Comment by core-man** [comment]
Do we really want to write a tutorial about markdown? Or we can give a brief introduction and list some online tutorials, e.g., https://help.coding.net/docs/management/markdown.html?

**Comment by seisman** [comment]
OK to me.

**Comment by core-man** [comment]
> OK to me.

I will first work on markdown soon.

**Comment by core-man** [comment]
I will work on bash.

**Comment by wangliang1989** [comment]
为什么没有perl？我知道你们认为perl已经过时了。但是我还是觉得perl在调用其他程序的时候方便太多了。另外，我觉得可以注意增加脚本语言对sac、gmt和系统命令的调用的写法

**Comment by seisman** [comment]
Perl is dead.

**Comment by core-man** [comment]
> 另外，我觉得可以注意增加脚本语言对sac、gmt和系统命令的调用的写法

我们主推和维护 Python，并且这也是目前最先进。因此，新手不需要学习 Perl 以及脚本语言调用 sac、gmt 和系统命令。

**Comment by wangliang1989** [comment]
python调用gmt都不学的话，那就要学pygmt？

**Comment by core-man** [comment]
> python调用gmt都不学的话，那就要学pygmt？

yes, pygmt is highly recommended.

**Comment by seisman** [comment]
Python调用系统命令或者sac gmt之类的，并没有啥难度

**Comment by wangliang1989** [comment]
> Python调用系统命令或者sac gmt之类的，并没有啥难度

真的建议你们还是加上，那天我查了很久都没有查到合适python调用gmt的写法，不然我不会问你。我觉得pygmt看着，我表示不想学。

**Comment by wangliang1989** [comment]
shell编程应该特别强调管道，这是Linux的一个重要思想

**Comment by core-man** [comment]
> shell编程应该特别强调管道，这是Linux的一个重要思想

shell 不建议编程使用

**Comment by core-man** [comment]
这只是初级入门教程，我们还是应该介绍最好用和先进的。用户可以自己在实际科研中选择自己喜欢的。

**Comment by core-man** [comment]
> Python调用系统命令或者sac gmt之类的，并没有啥难度

sac手册不是有python调用sac脚本吗？sac软件包里也自带有python脚本

**Comment by wangliang1989** [comment]
> > Python调用系统命令或者sac gmt之类的，并没有啥难度
> 
> sac手册不是有python调用sac脚本吗？sac软件包里也自带有python脚本

我当时认为脚本里储存一个超长的字符串不是件好事。

**Comment by core-man** [comment]
科研入门教程主要对象是新手，所以内容应该关注在当前最流行和必须要掌握的东西上。脚本语言对sac，gmt和系统命令的调用虽然一些用户需要和喜欢，但大部分时候可以被更好的方式替换。

说到底这个教程只是一个3天培训课，并不是参考书。如果真的有一定数目的老用户确实需要，那可以在其他参考书网站维护，如software，seismology，甚至sac和gmt的中文参考书中。

**Comment by core-man** [comment]
> > Python调用系统命令或者sac gmt之类的，并没有啥难度
> 
> 真的建议你们还是加上，那天我查了很久都没有查到合适python调用gmt的写法，不然我不会问你。我觉得pygmt看着，我表示不想学。

真心建议用pygmt，自己用python调用gmt很痛苦。pygmt维护得很好用现在。早用早享受~

**Comment by seisman** [comment]
I'm thinking about what we should do with the "Programming Languages" sections. Do we really want to write tutorials for each programming language? My answer is **NO**.

Here are my reasons:

1. There are already many good books or good online tutorials. We definitely can't write tutorials better than them.
2. We can write a short, simple tutorial like https://learnxinyminutes.com/docs/zh-cn/python-cn/, but how long does it take to go through the whole tutorial in class? 30-minutes or 1-hour? I don't think any students can remember Python syntax in 1-hour.

Take Python as an example, I think we should include the following information in the Python tutorial:

1. Introduce Anaconda and install it
2. Write a simple Python script in VSCode and explain what a Python script looks like
3. How to run a Python script in a terminal or directly in vscode
4. Introduce Jupyter Notebook, because it's popular and powerful
5. Introduce a few packages, like numpy, scipy and matplotlib and show a few examples.
6. How to install pacakges? mamba, conda, and pip
7. Provide more learning resources.

**Comment by seisman** [comment]
Closing the issue and see #469 and #470 instead.
