### ISSUE TITLE
BSD and GNU incompatibility

### ISSUE THREAD

**Issue by seisman** [seismo-learn/seismology101#91]
As mentioned in https://github.com/seismo-learn/seismology101/issues/90#issuecomment-762053884, the awk from macOS is different from the GNU awk. Actually there are more problems. Most utilities provided by macOS are BSD implementation, while the utilities on Linux are usually GNU implementation. BSD and GNU implementations may be similar or different.

Here are a list of utilities that may have incompatibility issues:

1. awk: Homebrew gawk provides both `awk` and `gawk` (the former is just a symbolic link of `gawk`), which overrides the BSD awk
2. sed: Homebrew sed is called `gsed`
3. tar: Homebrew tar is called `gtar`

We are not going to document the differences but at least we should add a note, as most online resources use GNU utilities, not BSD ones.

Related posts:

1. https://ponderthebits.com/2017/01/know-your-tools-linux-gnu-vs-mac-bsd-command-line-utilities-grep-strings-sed-and-find/
2. https://www.topbug.net/blog/2013/04/14/install-and-use-gnu-command-line-tools-in-mac-os-x/
3. https://gist.github.com/skyzyx/3438280b18e4f7c490db8a2a2ca0b9da
4. https://gist.github.com/skyzyx/3438280b18e4f7c490db8a2a2ca0b9da#gistcomment-3049694

**Comment by core-man** [comment]
So, we should use `brew` to install `sed` and `tar`? Then, we use `gsed` and `gtar`, right?

**Comment by seisman** [comment]
It's a little more complicated. See the second link above.

**Comment by core-man** [comment]
> It's a little more complicated. See the second link above.

This blog is great~

**Comment by seisman** [comment]
Will read that post carefully and have more in-depth discussions later.

**Comment by core-man** [comment]
> Will read that post carefully and have more in-depth discussions later.

Okay. We may add a detailed note or even a single section following the blog.

**Comment by seisman** [comment]
Please note that the above link 2 is no longer valid, and we should follow links 3 and 4, instead.

**Comment by seisman** [comment]
I feel it a little dangerous to replace all BSD utilities with GNU ones, as it may break some macOS-specific scripts.

**Comment by core-man** [comment]
> I feel it a little dangerous to replace all BSD utilities with GNU ones, as it may break some macOS-specific scripts.
> 
> I think what we can do is
> 
> 1. Installing these GNU tools
> 2. Run the GNU tools by using the `g` prefix (e.g., `gsed` for GNU, `sed` for BSD) when necessary

I agree.
